import { useEffect, useState } from 'react'
import { PageHero } from '../components/common/PageHero'
import { founderApplicationSchema } from '../lib/validation/application'
import { submitFounderApplication } from '../lib/supabase/repository'

const initial:any={fullName:'',email:'',phone:'',city:'',role:'',company:'',idea:'',problem:'',customer:'',stage:'',industry:'',conversations:0,evidence:'',assumption:'',competitors:'',why:'',weeklyHours:1,team:'',built:'',bottleneck:'',support:'',next30:'',accurate:false,privacy:false,contact:false,acknowledge:false}
const steps=[['Founder',['fullName','email','phone','city','role']],['Company or idea',['company','idea','problem','customer','stage','industry']],['Evidence',['conversations','evidence','assumption','competitors']],['Founder commitment',['why','weeklyHours','team','built','bottleneck','support','next30']],['Consent & review',['accurate','privacy','contact','acknowledge']]] as const
const labels:any={fullName:'Full name',email:'Email',phone:'Phone / WhatsApp (private)',city:'City and state',role:'Current role / status',company:'Startup / company name (optional)',idea:'One-sentence idea',problem:'Problem being solved',customer:'Target customer',stage:'Current stage',industry:'Industry',conversations:'Number of customer conversations completed',evidence:'Strongest evidence that the problem matters',assumption:'Biggest assumption still untested',competitors:'Current alternatives or competitors',why:'Why this problem matters personally',weeklyHours:'Weekly hours available',team:'Team / co-founders',built:'What has already been built',bottleneck:'Biggest current bottleneck',support:'What support is needed',next30:'What will you complete in the next 30 days'}
export default function Apply(){const [step,setStep]=useState(0);const [data,setData]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem('uniqgro-application')||'null')||initial}catch{return initial}});const [error,setError]=useState('');const [done,setDone]=useState(false);useEffect(()=>{localStorage.setItem('uniqgro-application',JSON.stringify(data))},[data]);const fields=steps[step][1];function input(name:string){const isLong=['problem','evidence','assumption','why','built','bottleneck','support','next30'].includes(name);const type=['conversations','weeklyHours'].includes(name)?'number':name==='email'?'email':'text';return <div className={`field ${isLong?'full':''}`} key={name}><label htmlFor={name}>{labels[name]}</label>{isLong?<textarea id={name} className="textarea" rows={4} value={data[name]} onChange={e=>setData({...data,[name]:e.target.value})}/>:<input id={name} className="input" type={type} value={data[name]} onChange={e=>setData({...data,[name]:type==='number'?Number(e.target.value):e.target.value})}/>}</div>}
async function submit(){setError('');const parsed=founderApplicationSchema.safeParse(data);if(!parsed.success){setError('Please review the form. Some required answers are incomplete or invalid.');return}try{await submitFounderApplication(parsed.data);localStorage.removeItem('uniqgro-application');setDone(true)}catch{setError('Submission could not be delivered. Check Supabase configuration and try again.')}}
if(done)return <><PageHero eyebrow="APPLICATION RECEIVED" title="Your application is in." lead="The next step is not a pitch—it is a closer look at the problem, the evidence and your commitment to execute."/></>
return <><PageHero eyebrow="FOUNDER APPLICATION" title="START WITH THE TRUTH. BUILD FROM THERE." lead="Five steps. Autosaved locally on this device until submission."/><section className="section"><div className="container form-shell"><div className="eyebrow">STEP {step+1} OF 5 · {steps[step][0]}</div><div className="progress"><i style={{width:`${((step+1)/5)*100}%`}}/></div>{error&&<div className="notice">{error}</div>}<div className="form-grid">{step<4?fields.map(f=>input(f as string)):<>{[['accurate','I confirm that the information I provided is accurate.'],['privacy','I consent to the processing of this application for founder-selection and contact purposes.'],['contact','UniqGro may contact me about this application.'],['acknowledge','I understand that applying does not guarantee selection, funding, revenue or services.']].map(([name,text])=><label className="checkbox field full" key={name}><input type="checkbox" checked={data[name]} onChange={e=>setData({...data,[name]:e.target.checked})}/><span>{text}</span></label>)}<div className="notice field full"><strong>Review</strong><p>{data.fullName || 'Founder'} · {data.idea || 'Idea not yet entered'}</p><p>Your private phone number is collected only through the application flow and is not displayed publicly.</p></div></>}</div><div className="form-nav"><button className="btn ghost" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>Back</button>{step<4?<button className="btn primary" onClick={()=>setStep(step+1)}>Continue</button>:<button className="btn primary" onClick={submit}>Submit application</button>}</div></div></section></>}
