import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight } from 'lucide-react'
import { HeroNetwork } from '../components/common/HeroNetwork'
import { FounderJourney } from '../components/journey/FounderJourney'
import { site } from '../content/site'
import { SEO } from '../lib/seo/SEO'

const caps=['Startup Diagnosis & Strategic Clarity','Customer Discovery & Idea Validation','Positioning, Naming & Brand Direction','Offer Design & Business Model','Go-to-Market Planning','Content, Marketing & Demand Experiments','Sales Process & Business Development','Retention & Customer Experience','AI Workflows & Operational Automation','SOPs, Scorecards & Team Systems','Franchise and Expansion Readiness','Founder Accountability & Community']
const reasons=[['We start early','Support begins before traction.'],['We think founder-to-founder','Partnership, not distance.'],['We connect the work','Strategy, brand, growth and systems reinforce one another.'],['We test before scaling','Evidence before expensive decisions.'],['We document progress','Scorecards, learnings and SOPs become company assets.'],['We build for independence','The founder should become stronger, not permanently dependent.']]
export default function Home(){return <>
<SEO title="UniqGro — Build Companies. Not Alone." description="UniqGro is a founder-first ecosystem built in India for idea-stage and early-stage founders who need clarity, validation, execution and community."/>
<section className="hero"><div className="container hero-grid"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.55}}><div className="eyebrow">FOUNDER-FIRST · EXECUTION-LED · BUILT IN INDIA</div><h1 className="display">BUILD<br/>COMPANIES.<br/><em>NOT ALONE.</em></h1><p className="lead">UniqGro is an idea-stage founder ecosystem that brings strategy, validation, brand, execution and community into one connected journey.</p><div className="actions"><Link className="btn primary" to="/apply">Apply to Build <ArrowRight size={17}/></Link><Link className="btn ghost" to="/how-it-works">See How It Works</Link></div><p style={{opacity:.6,fontSize:'.86rem',marginTop:18}}>Begin with a founder diagnostic. No pressure. No generic pitch.</p></motion.div><HeroNetwork/></div></section>
<section className="manifesto"><div className="container"><div className="eyebrow">THE BEGINNING</div><h2>Most startup support begins after traction.<span>We begin when all you have is an idea—and the conviction to build it.</span></h2></div></section>
<section className="section"><div className="container"><div className="eyebrow">THE SUPPORT GAP</div><h2 className="section-title">Who stands beside the founder before the proof exists?</h2><div className="grid4"><article><h3>VCs</h3><p>Usually enter after evidence.</p></article><article><h3>Investors</h3><p>Usually enter when growth is visible.</p></article><article><h3>Accelerators</h3><p>Often select after early validation.</p></article><article style={{background:'var(--color-cobalt)',color:'#fff'}}><h3>UniqGro</h3><p>Built to help founders create the first credible proof.</p></article></div><p style={{fontSize:'1.4rem',marginTop:28}}>That is the space UniqGro is built to serve.</p></div></section>
<section className="section dark"><div className="container"><div className="eyebrow">NOT AN AGENCY</div><h2 className="section-title">Execution should create evidence, not dependence.</h2><div className="split"><div><h3>Not this</h3><ul className="bullets"><li>Advice without accountability.</li><li>A collection of disconnected services.</li><li>Vanity metrics and guaranteed-growth promises.</li><li>An outsourced team replacing the founder.</li></ul></div><div><h3>Built for this</h3><ul className="bullets"><li>Clear decisions grounded in evidence.</li><li>Strategy connected directly to execution.</li><li>Shared scorecards and founder accountability.</li><li>Systems that remain useful after the engagement.</li></ul></div></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">THE FOUNDER JOURNEY</div><h2 className="section-title">From uncertainty to a repeatable system.</h2><FounderJourney/><div className="actions"><Link className="btn primary" to="/how-it-works">Explore the complete founder journey</Link></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">CAPABILITIES, ACTIVATED AT THE RIGHT STAGE</div><h2 className="section-title">Build what the next decision requires.</h2><div className="cards">{caps.map((c,i)=><article className="card" key={c}><div className="eyebrow">{String(i+1).padStart(2,'0')}</div><h3>{c}</h3><p>Problem → build → founder contribution → evidence of progress.</p></article>)}</div></div></section>
<section className="section dark"><div className="container"><div className="eyebrow">COMMUNITY NETWORK</div><h2 className="section-title">A company needs more than one kind of mind.</h2><div className="role-network">{['Founders','Strategists','Builders','Operators'].map(x=><div className="role" key={x}><h3>{x}</h3><p>Serious people working through real problems, decisions and execution.</p></div>)}</div><p className="lead" style={{marginTop:30}}>UniqGro connects people who are serious about building—not collecting contacts. Ask better questions, share practical knowledge, find collaborators and stay accountable to real progress.</p><Link className="btn primary" to="/community">Enter the Community</Link></div></section>
<section className="section"><div className="container portrait-layout"><div className="portrait"><img src={site.founder.image} alt="Portrait of Gourav Saini, Founder and CEO of UniqGro" loading="lazy"/></div><div><div className="eyebrow">FOUNDER NOTE</div><blockquote className="quote">“I’m building UniqGro as a founder—not as an outsider looking at founders from a distance. The goal is to create the kind of partnership that stays close to the problem, the decisions and the execution.”</blockquote><strong>{site.founder.name}</strong><p>{site.founder.role} · {site.founder.responsibility}</p><Link className="btn ghost" to="/founder">Read the Founder Story</Link></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">WHY FOUNDERS CHOOSE UNIQGRO</div><div className="cards">{reasons.map(([h,p])=><article className="card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
<section className="section blue"><div className="container"><div className="eyebrow" style={{color:'#fff'}}>FOUNDER APPLICATIONS</div><h2 className="section-title">Bring the idea. Bring the truth. Bring the commitment.</h2><p className="lead">You do not need perfect slides, funding or all the answers. You do need a real problem, the willingness to speak with customers and the commitment to execute.</p><Link className="btn" to="/apply">Apply to Build with UniqGro</Link></div></section>
<section className="official"><div className="container"><h2>WE DON’T WORK FOR FOUNDERS.<span>WE WORK WITH FOUNDERS.</span></h2><p className="lead" style={{margin:'28px auto'}}>Build the next step with people who understand the beginning.</p><div className="actions" style={{justifyContent:'center'}}><Link className="btn primary" to="/apply">Apply to Build</Link><Link className="btn ghost" to="/community">Join the Community</Link></div></div></section>
</>}
